homework5
lavrov97/bomba pull request #1
Opened 2021-01-30 18:08 UTC by lavrov97

Homework5

2021-02-01 15:45 UTC, lavrov97 commented
`Homework 5

2021-02-04 12:55 UTC, RomanKashenok requested changes

2021-02-04 12:55 UTC, RomanKashenok commented on lesson 5/src/Example13.java
> +        for (int i = 1; i <= 2564; i *= 2) {
прям честно скопировано ))

2021-02-04 12:55 UTC, RomanKashenok commented on lesson 5/src/Example2.java
> +        for (int i=10; i<15; i++){
пусть так. Но я имел в виду взять любое число в этих границах и посчитать его факториал )

2021-02-04 12:55 UTC, RomanKashenok commented on lesson 5/src/Example3.java
> +        int i;
а зачем тут i объявляешь? Если больше нигде его не планируешь использовать - объявляй i прямо в блоке уловия цикла

2021-02-04 12:55 UTC, RomanKashenok commented on lesson 5/src/Example8.java
> +        for (int x = 1; x < array.length - 1; x++) {
Честно скопировано? Или у тебя скопировани неправильное решение? 
Ты по сути посчитал сумму всех элементов массива, а не сумму элементов между минимальным и максимальным. Так что сортировать не нужно

2021-02-04 12:55 UTC, RomanKashenok commented on lesson 5/src/Example9.java
> +public class Example9 {
Тут вот гуд ))

2021-02-04 12:55 UTC, RomanKashenok commented on lesson 5/src/Exapmle4.java
> +            for (int i = 1; i <= 100; i++) {
а если я захочу сумму первых 150 чисел, которые делятся на 3 ?

2021-02-06 11:25 UTC, merged